# Generated by Django 3.0.7 on 2021-05-20 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField()),
                ('dob', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
